apiVersion: ebpf-kube-agent.org/v1alpha1
kind: kprobe
metadata:
  name: sys_execve
spec:
  mode: once
  selector: 
    namespaces:
      - default
    labelSelectors:
      'app': 'backend' 
  duration: '10s'
  program: "I2luY2x1ZGUgImNvbW1vbi5oIgoKY2hhciBfX2xpY2Vuc2VbXSBTRUMoImxpY2Vuc2UiKSA9ICJEdWFsIE1JVC9HUEwiOwoKc3RydWN0IGJwZl9tYXBfZGVmIFNFQygibWFwcyIpIGtwcm9iZV9tYXAgPSB7CgkudHlwZSAgICAgICAgPSBCUEZfTUFQX1RZUEVfUEVSQ1BVX0FSUkFZLAoJLmtleV9zaXplICAgID0gc2l6ZW9mKHUzMiksCgkudmFsdWVfc2l6ZSAgPSBzaXplb2YodTY0KSwKCS5tYXhfZW50cmllcyA9IDEsCn07CgpTRUMoImtwcm9iZS9zeXNfZXhlY3ZlIikKaW50IGtwcm9iZV9leGVjdmUoKSB7Cgl1MzIga2V5ICAgICA9IDA7Cgl1NjQgaW5pdHZhbCA9IDEsICp2YWxwOwoKCXZhbHAgPSBicGZfbWFwX2xvb2t1cF9lbGVtKCZrcHJvYmVfbWFwLCAma2V5KTsKCWlmICghdmFscCkgewoJCWJwZl9tYXBfdXBkYXRlX2VsZW0oJmtwcm9iZV9tYXAsICZrZXksICZpbml0dmFsLCBCUEZfQU5ZKTsKCQlyZXR1cm4gMDsKCX0KCV9fc3luY19mZXRjaF9hbmRfYWRkKHZhbHAsIDEpOwoKCXJldHVybiAwOwp9" # base64编码