apiVersion: v1
kind: Service
metadata:
  namespace: "ebpf-kube-agent"
  name: ebpf-agent
  labels:
    app.kubernetes.io/name: ebpf-kube-agent
    app.kubernetes.io/instance: ebpf-kube-agent
    app.kubernetes.io/part-of: ebpf-kube-agent
    app.kubernetes.io/version: ${VERSION_TAG##v}
    app.kubernetes.io/component: ebpf-agent
spec:
  clusterIP: None
  ports:
    - name: http
      port: 2333
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: ebpf-kube-agent
    app.kubernetes.io/instance: ebpf-kube-agent
    app.kubernetes.io/component: ebpf-agent